name: deploy

on:
  # trigger build on every push to main branch
  push:
    branches: main
  # trigger build on every pull request
  pull_request:
  # trigger deployment manually
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # choose node.js version to use
          node-version: "22"
          cache: 'yarn'

      # install dependencies
      - name: Install node.js dependencies
        run: yarn

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          # choose python version to use
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: "tasks/requirements.txt"

      - name: Install python dependencies
        run: pip install -r tasks/requirements.txt

      # generate link variants
      - name: Generate link variants
        run: python tasks/generate_link_variants.py

      # run build script
      - name: Build json files
        run: node deploy.js

      # run calendar script
      - name: Generate calendar
        run: python tasks/gen_calendar.py

      # please check out the docs of the workflow for more details
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        if: (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')) || github.event_name == 'workflow_dispatch'
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # deploy to gh-pages branch
          target_branch: gh-pages
          # deploy the default output dir of VuePress
          build_dir: out
        env:
          # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install node.js dependencies
        run: yarn

      - name: Validate Schema
        run: yarn validate
